from __future__ import annotations

import hashlib

from signalops.models import CRMRecord


TOP_ACCOUNTS = [
    {
        "company_name": "Factorial",
        "domain": "factorialhr.com",
        "perk_fit_score": 94,
        "confidence": 0.88,
        "primary_pain": "scaling finance, HR, IT, travel, and spend controls across expanding European offices",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "finance_led",
        "owner_queue": "emea_mid_market_finance_led",
        "next_best_action": "Route to EMEA Mid-Market AE; lead with Germany expansion, finance workflows, and policy-controlled travel/spend.",
        "research_summary": "Factorial is a Barcelona-based AI business software company with around 1,700 employees and expansion momentum in Germany. Its HR, finance, and IT workflow footprint makes it a strong fit for Perk's travel, expense, invoice, and spend-management story.",
    },
    {
        "company_name": "Legora",
        "domain": "legora.com",
        "perk_fit_score": 92,
        "confidence": 0.84,
        "primary_pain": "rapid headcount growth, enterprise sales travel, and multi-country operating complexity",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "general_outbound",
        "owner_queue": "emea_mid_market_general_outbound",
        "next_best_action": "Send to growth-account outbound; verify finance or operations owner and reference rapid international hiring.",
        "research_summary": "Legora is a fast-growing legal AI company with public reports of major headcount expansion and enterprise customer demand. Rapid scaling from Sweden into broader markets likely creates travel, events, approvals, and spend visibility needs.",
    },
    {
        "company_name": "Synthesia",
        "domain": "synthesia.io",
        "perk_fit_score": 91,
        "confidence": 0.86,
        "primary_pain": "global enterprise sales, customer events, and distributed team travel",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "events_led",
        "owner_queue": "emea_mid_market_events_led",
        "next_best_action": "Route to enterprise-growth outbound; lead with sales travel, global customer events, and automated expense reporting.",
        "research_summary": "Synthesia is a London-based AI video company serving large enterprise customers and expanding internationally. Its global customer base, sales motion, and distributed teams are strong Perk-fit signals.",
    },
    {
        "company_name": "Pigment",
        "domain": "pigment.com",
        "perk_fit_score": 89,
        "confidence": 0.82,
        "primary_pain": "finance-led planning teams needing better travel, expense, invoice, and spend visibility",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "finance_led",
        "owner_queue": "emea_mid_market_finance_led",
        "next_best_action": "Route to finance-led outbound; target CFO, finance operations, or business operations personas.",
        "research_summary": "Pigment sells business planning software to finance, sales, HR, and operations teams. The finance buyer overlap and international enterprise motion make it a high-quality Perk target.",
    },
    {
        "company_name": "Mistral AI",
        "domain": "mistral.ai",
        "perk_fit_score": 88,
        "confidence": 0.8,
        "primary_pain": "cross-border expansion, US sales buildout, and executive travel coordination",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "general_outbound",
        "owner_queue": "emea_mid_market_general_outbound",
        "next_best_action": "Route to strategic outbound; verify current finance ops owner and reference Europe-to-US expansion.",
        "research_summary": "Mistral AI is a leading European AI company with public expansion into Silicon Valley and US sales hiring signals. Cross-border growth suggests meaningful travel, approval, and spend-management complexity.",
    },
    {
        "company_name": "Helsing",
        "domain": "helsing.ai",
        "perk_fit_score": 87,
        "confidence": 0.79,
        "primary_pain": "multi-country defense operations, procurement controls, and policy-heavy travel",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "finance_led",
        "owner_queue": "emea_mid_market_finance_led",
        "next_best_action": "Send to human-assisted strategic review before outreach; confirm procurement and security constraints.",
        "research_summary": "Helsing is a Munich-based defense AI company with subsidiaries and manufacturing activity across Europe. It appears relevant for controlled travel, procurement, and spend governance, but its defense context warrants careful human review.",
    },
    {
        "company_name": "Miro",
        "domain": "miro.com",
        "perk_fit_score": 85,
        "confidence": 0.83,
        "primary_pain": "large distributed workforce, enterprise sales travel, and customer event operations",
        "segment": "enterprise",
        "region": "Global",
        "sales_motion": "events_led",
        "owner_queue": "global_enterprise_events_led",
        "next_best_action": "Route to Enterprise outbound; lead with global event operations and distributed team travel controls.",
        "research_summary": "Miro has a large global user base, headquarters presence in Amsterdam and San Francisco, and a distributed enterprise collaboration motion. It is a strong fit for travel, events, and expense process automation.",
    },
    {
        "company_name": "Qonto",
        "domain": "qonto.com",
        "perk_fit_score": 82,
        "confidence": 0.78,
        "primary_pain": "European market expansion and multi-country finance operations",
        "segment": "enterprise",
        "region": "EMEA",
        "sales_motion": "finance_led",
        "owner_queue": "emea_enterprise_finance_led",
        "next_best_action": "Route to finance-led review; validate competitive overlap and identify travel/spend use case outside core banking product.",
        "research_summary": "Qonto is a European business finance platform operating across multiple markets with around 1,600 employees. It has strong finance-operations signals, though product overlap means outreach should be reviewed carefully.",
    },
    {
        "company_name": "Contentful",
        "domain": "contentful.com",
        "perk_fit_score": 81,
        "confidence": 0.8,
        "primary_pain": "multi-office SaaS operations, customer success travel, and field sales expenses",
        "segment": "mid_market",
        "region": "Global",
        "sales_motion": "general_outbound",
        "owner_queue": "global_mid_market_general_outbound",
        "next_best_action": "Route to global SaaS outbound; lead with multi-office travel policy and expense automation.",
        "research_summary": "Contentful is a B2B SaaS company with offices across the US, Europe, and Australia. Its enterprise customer base and multi-office footprint suggest travel and spend-management needs.",
    },
    {
        "company_name": "Alan",
        "domain": "alan.com",
        "perk_fit_score": 79,
        "confidence": 0.76,
        "primary_pain": "regulated multi-country growth with finance, operations, and team travel needs",
        "segment": "mid_market",
        "region": "EMEA",
        "sales_motion": "general_outbound",
        "owner_queue": "emea_mid_market_general_outbound",
        "next_best_action": "Route to EMEA outbound; verify current operations owner and reference multi-country growth.",
        "research_summary": "Alan is a French health insurance scaleup active in several markets including France, Belgium, Spain, and Canada. Multi-country regulated operations make it a plausible Perk-fit account.",
    },
]


def seed_records() -> list[CRMRecord]:
    return [
        CRMRecord(
            account_id=account_id(account["domain"]),
            company_name=account["company_name"],
            domain=account["domain"],
            perk_fit_score=account["perk_fit_score"],
            confidence=account["confidence"],
            primary_pain=account["primary_pain"],
            route_decision="auto_qualify",
            segment=account["segment"],
            region=account["region"],
            sales_motion=account["sales_motion"],
            owner_queue=account["owner_queue"],
            next_best_action=account["next_best_action"],
            human_review_reason="Manually researched seed account for initial RevOps target list.",
            research_summary=account["research_summary"],
        )
        for account in TOP_ACCOUNTS
    ]


def account_id(domain: str) -> str:
    return "acct_" + hashlib.sha1(domain.lower().encode("utf-8")).hexdigest()[:12]
